name: Swagger code generator

on: [push]

jobs:
  generate:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@master    
    - name: save_controllers
      run: ./cp server/swagger_server/controllers/*_controller.py . # save our implementation for later use
    - uses: ducksify/swagger-codegen-action@V3.0
      with:
        args: >
          -i server/swagger_server/swagger/swagger.yaml 
          -l python-flask 
          -o server
    - name: restore controllers
      run: |
        echo saving generated controllers to controllers_new
        for filename in server/swagger_server/controllers/*_controller.py; # renaming file
        do
        mv "$filename" "$(echo "$filename" | sed s/_controller.py/_controller_template.py/)";
        done

        echo restoring controllers
        cp *_controller.py server/swagger_server/controllers/
        rm *_controller.py
    - uses: stefanzweifel/git-auto-commit-action@v4 # commiting changes
