---
swagger: "2.0"
info:
  description: "Simple IP balanser"
  version: "1.0.0"
  title: "Ipefr servers Balancer"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "vinogradov.alek@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost"
basePath: "/"
tags:
- name: "server"
  description: "servers load balanser"
schemes:
- "http"
paths:
  /server:
    get:
      tags:
      - "server"
      summary: "optain server IP"
      description: "Multiple status values can be provided with comma separated strings"
      operationId: "get_ip"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Results"
        "503":
          description: "Server Unavailible"
      security:
      - server_auth:
        - "read:server"
      x-swagger-router-controller: "swagger_server.controllers.server_controller"
    post:
      tags:
      - "server"
      summary: "send server ip to balancer"
      description: ""
      operationId: "post_ip"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Results"
        "405":
          description: "Invalid input"
      security:
      - server_auth:
        - "write:server"
      x-swagger-router-controller: "swagger_server.controllers.server_controller"
    delete:
      tags:
      - "server"
      summary: "delete server IP"
      description: "Send by server during shutdown"
      operationId: "delete_ip"
      produces:
      - "application/Json"
      parameters: []
      responses:
        "200":
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Results"
        "400":
          description: "Request failed"
      security:
      - server_auth:
        - "write:server"
      x-swagger-router-controller: "swagger_server.controllers.server_controller"
securityDefinitions:
  server_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:server: "post server info"
      read:server: "get server info"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Results:
    type: "object"
    properties:
      ipv4:
        type: "string"
        example: "192.168.0.2"
        minLength: 8
        maxLength: 16
      port:
        type: "integer"
        example: 5201
    example:
      ipv4: "192.168.0.2"
      port: 5201
