---
swagger: "2.0"
info:
  description: "Simple IP balanser"
  version: "1.0.0"
  title: "Ipefr servers Balancer"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "vinogradov.alek@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost"
basePath: "/v2"
tags:
- name: "server"
  description: "servers load balanser"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
schemes:
- "https"
- "http"
paths:
  /server:
    get:
      tags:
      - "server"
      summary: "optain server IP"
      description: "Multiple status values can be provided with comma separated strings"
      operationId: "get_results"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Results"
        "400":
          description: "Invalid status value"
      x-swagger-router-controller: "swagger_server.controllers.server_controller"
    post:
      tags:
      - "server"
      summary: "send server ip to server"
      description: ""
      operationId: "do_action"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "OK"
        "405":
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.server_controller"
definitions:
  Results:
    type: "object"
    properties:
      ipv4:
        type: "string"
        example: "192.168.0.2"
        minLength: 8
        maxLength: 16
    example:
      ipv4: "192.168.0.2"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
